name: broadband-usage-report-cron

on:
  schedule: 
    - cron: "45 5,11,17,23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Call the function
        run: wget 'https://us-central1-npm-downloads-reporter.cloudfunctions.net/broadbandUsage'
