name: broadband-usage-report

on:
  schedule: 
    - cron: '20 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Call the function
        run: wget 'https://us-central1-npm-downloads-reporter.cloudfunctions.net/broadbandUsage?message=true'
